### ISSUE TITLE
Extension gone from the Chrome Web Store

### ISSUE THREAD

**Issue by fregante** [jdm-contrib/justdelete.me-chrome-extension#11]
Just opening this issue for reference. See

- https://github.com/jdm-contrib/jdm/issues/1772

**Comment by fregante** [comment]
Now available at:

- https://chrome.google.com/webstore/detail/just-delete-me/dlhckcablohllindinahbbpnfgblimoe
- https://github.com/fregante/jdm (source)

**Comment by tupaschoal** [comment]
Info seen on [eb6aaa9](https://github.com/jdm-contrib/justdelete.me-chrome-extension/commit/eb6aaa9af234d95710c923bbedb1a7c4de748ff2)
