### ISSUE TITLE
 Porting to supported version of justdelete.me

### ISSUE THREAD

**Issue by tupaschoal** [jdm-contrib/justdelete.me-chrome-extension#2]
The main justdelete.me repository has been abandoned and we're trying to keep it alive on a detached fork [here](https://github.com/jdm-contrib), would you be interested in transferring the repo to the jdm-contrib organization? 

If we do we can assure it is kept up-to-date and, since we have gathered some people on the org, not let the project get stale.

Thanks :)

**Comment by rugk** [comment]
Actually maybe merging this extension with the [Firefox one](https://github.com/alaouy/justdelete.me-firefox-addon) would also be a good idea, as they are both WebExtensions and could be made to work with both browsers.

**Comment by MikeRogers0** [comment]
I just talked with @rmlewisuk :)

I like both these ideas. I'm happy to transfer the repo over to you :)

**Comment by tupaschoal** [comment]
Great @MikeRogers0 !

**Comment by MikeRogers0** [comment]
Awesome @tupaschoal ! Give me permission to transfer & I'll jump on it!

**Comment by tupaschoal** [comment]
I don't know how to do it, lol!

You can transfer to me and I will transfer it to the org, that's what we did with the firefox extension :p

**Comment by MikeRogers0** [comment]
@tupaschoal Go to https://github.com/jdm-contrib/settings/member_privileges & add me as a member, then I should be able to.

**Comment by PyroSamurai** [comment]
@MikeRogers0 I've taken care of it and added you to a team so that you can transfer/maintain the repo.
